# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# Append to the history file, don't overwrite it
shopt -s histappend

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# Filenames starting with . are included in * pathname expansion
shopt -s dotglob

export bash_dir="$XDG_CONFIG_HOME/bash"
function source_b() {
  source "${bash_dir}/${1}.bash"
}
export -f source_b

case "$TERM" in
xterm*|rxvt*)
  source_b colors
  ;;
*)
  ;;
esac

source_b aliases
