#!/usr/bin/env bash

function feature_ssh {
  pka openssh openssh-clients
  ssh-keygen -t ed25519 -C "$SECRETS_EMAIL"
  eval "$(ssh-agent -s)"
  ssh-add ~/.ssh/id_ed25519

  #dir="~/.ssh"
  #file="$dir/id_ed25519"
  #mkdir -p "$dir"
  #echo "$SECRETS_SSH_PRIVATE_KEY" >  $file
  #echo "$SECRETS_SSH_PUBLIC_KEY" >  "$file".pub
  #chmod 700 $dir
  #chmod 600 $file
  #chmod 644 "$file".pub
}
