#!/usr/bin/env bash

pki gnupg
gpg --full-generate-key
key_id=$(gpg --list-secret-keys --keyid-format=long | grep sec | awk '{print $2}' | cut -d '/' -f2)

gpg --armor --export "$key_id" | clp
echo 'Copied GPG key ID to clipboard, in ASCII armor format'
