#!/usr/bin/env bash

arch="$(uname -m)"
case "$arch" in
    x86_64)
        arch='amd64'
        ;;
    aarch64)
        arch='arm64'
        ;;
    armv7l)
        arch='arm'
        ;;
    ppc64le)
        arch='ppc64le'
        ;;
    s390x)
        arch='s390x'
        ;;

    *)
        echo "Error: Unsupported platform $arch" >&2
        exit 1
        ;;
esac

wget https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-${arch} -O ~/.local/bin/minikube
chmod +x ~/.local/bin/minikube

