#!/usr/bin/env bash

profile=""
profile_json_schema=""

check_profile_json() {
  bad=""
  [ -n bad ] && exit
}

read_profile() {
  profile="$1"
  profile_json="$(cat ${CONFIGS_DIR}/profiles/${profile}/profile.json)"
  check_profile_json "$profile_json"
  echo ciao
}

function apply {
  echo "apply $@"
}

function init {
  echo "init $@"
}

function deploy {
  echo "deploy $@"
}


commands=('init' 'apply' 'deploy')

function main {
  cmd=$1
  shift
  found=false
  for c in "${commands[@]}"; do
    if [[ "$cmd" == "$c" ]]; then
      found=true
      break
    fi
  done
  if ! $found; then
    echo "Command $cmd not found" >&2
    exit 1
  fi
  echo "$@"
  "$cmd" "$@"
}

#-----

#TEST=1
if [ -z "$TEST" ]; then
  main $@
else

  export CONFIGS_DIR="$HOME/git/configs"
  export PROFILE='debian'

  function test_read_profile {
    read_profile
  }

  function test {
    test_read_profile
  }

  echo 'testing...'
  test

fi
