#!/usr/bin/env bash

profile=""
profile_json_schema=""

function check_profile_json {
  bad=""
  [ -n bad ] && exit
}

function read_profile {
  profile="$1"
  profile_json="$(cat ${CONFIGS_DIR}/profiles/${profile}/profile.json)"
  check_profile_json "$profile_json"
  echo ciao
  
}

function apply {
  echo "apply $@"
}

function init {
  echo "init $@"
}

function main {
  case $1 in
  'apply')
    apply "${@:2}"
    ;;
  esac
  'init')
    init "${@:2}"
    ;;
  esac

}

#-----

DEBUG=1
if [ -z "$DEBUG" ]; then
  main $@
else

  export CONFIGS_DIR="$HOME/git/configs"
  export PROFILE='debian'

  function test_read_profile {
    read_profile
  }

  function test {
    test_read_prof
  }

  echo 'debugging...'
  test

fi
